# Generated by Skyramp v1.3.14 on 2026-03-24 21:51:31.324368705 +0000 UTC m=+231.854568860
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_post_flow_costs.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--request-data {"flow_run_id":"3fa85f64-5717-4562-b3fc-2c963f66afa6","compute_seconds":120.5,"memory_mb":256.0,"external_cost_usd":0.05,"cost_center":"data-engineering"} \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs/ POST
def test_flow_costs_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flow_costs_POST_request_body = r'''{
        "compute_seconds": 120.5,
        "cost_center": "data-engineering",
        "external_cost_usd": 0.05,
        "flow_run_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "memory_mb": 256
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/flow-costs/",
        method="POST",
        status_code=200,
        request_body=flow_costs_POST_request_body
    )
    client.apply_mock(mock)

    # Execute Request
    flow_costs_POST_response = client.send_request(
        url=URL,
        path="/api/flow-costs/",
        method="POST",
        body=flow_costs_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(flow_costs_POST_response, "20x")

    client.remove_all_mocks()


if __name__ == "__main__":
    test_flow_costs_post()
