# Generated by Skyramp v1.3.14 on 2026-03-24 22:35:23.500590165 +0000 UTC m=+264.537740665
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs/summary/ \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output contract_get_flow_cost_summary.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs/summary/ GET
def test_summary_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/flow-costs/summary/",
        method="GET",
        status_code=200
    )
    client.apply_mock(mock)

    # Execute Request
    summary_GET_response = client.send_request(
        url=URL,
        path="/api/flow-costs/summary/",
        method="GET",
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(summary_GET_response, "20x")

    client.remove_all_mocks()


if __name__ == "__main__":
    test_summary_get()
