# Generated by Skyramp v1.3.14 on 2026-03-24 23:20:39.196236033 +0000 UTC m=+123.925026957
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs/ \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_flow_costs_post.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flow_run_id":"c9d8e7f6-a5b4-3210-fedc-ba9876543210","compute_seconds":60.0,"memory_mb":256.0,"external_cost_usd":0.0,"cost_center":"data-engineering"} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs/ POST
def test_flow_costs_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flow_costs_POST_request_body = r'''{
        "compute_seconds": 60,
        "cost_center": "data-engineering",
        "external_cost_usd": 0,
        "flow_run_id": "c9d8e7f6-a5b4-3210-fedc-ba9876543210",
        "memory_mb": 256
    }'''

    # Execute Request
    flow_costs_POST_response = client.send_request(
        url=URL,
        path="/api/flow-costs/",
        method="POST",
        body=flow_costs_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(flow_costs_POST_response, "20x")


if __name__ == "__main__":
    test_flow_costs_post()
