# Generated by Skyramp v1.3.14 on 2026-03-24 21:51:35.525883818 +0000 UTC m=+236.056083983
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs/budgets/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_post_flow_costs_budgets.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--request-data {"cost_center":"data-engineering","monthly_budget_usd":500.0,"alert_threshold_pct":80.0} \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs/budgets/ POST
def test_budgets_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    budgets_POST_request_body = r'''{
        "alert_threshold_pct": 80,
        "cost_center": "data-engineering",
        "monthly_budget_usd": 500
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/flow-costs/budgets/",
        method="POST",
        status_code=200,
        request_body=budgets_POST_request_body
    )
    client.apply_mock(mock)

    # Execute Request
    budgets_POST_response = client.send_request(
        url=URL,
        path="/api/flow-costs/budgets/",
        method="POST",
        body=budgets_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(budgets_POST_response, "20x")

    client.remove_all_mocks()


if __name__ == "__main__":
    test_budgets_post()
