# Generated by Skyramp v1.3.14 on 2026-03-24 23:21:20.456410302 +0000 UTC m=+159.850243996
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output contract_flow_costs_auth_boundary.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flow_run_id":"a1b2c3d4-e5f6-7890-abcd-ef1234567890","compute_seconds":120.5,"memory_mb":512.0,"external_cost_usd":0.05,"cost_center":"engineering"} \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs/ POST
def test_flow_costs_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flow_costs_POST_request_body = r'''{
        "compute_seconds": 120.5,
        "cost_center": "engineering",
        "external_cost_usd": 0.05,
        "flow_run_id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        "memory_mb": 512
    }'''

    # Execute Request
    flow_costs_POST_response = client.send_request(
        url=URL,
        path="/api/flow-costs/",
        method="POST",
        body=flow_costs_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert flow_costs_POST_response.status_code == 401


if __name__ == "__main__":
    test_flow_costs_post()
