# Generated by Skyramp v1.3.14 on 2026-03-24 22:35:29.906369188 +0000 UTC m=+270.943519688
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs/{cost_id} \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method PUT \
# 		--output contract_put_flow_cost_by_id.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params cost_id=3fa85f64-5717-4562-b3fc-2c963f66afa6 \
# 		--request-data {"compute_seconds":240.0,"memory_mb":512.0,"external_cost_usd":0.10} \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs/{cost_id} PUT
def test_api_flow_costs_cost_id_put():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    cost_id = "3fa85f64-5717-4562-b3fc-2c963f66afa6"

    # Request Body
    api_flow_costs_cost_id_PUT_request_body = r'''{
        "compute_seconds": 240,
        "external_cost_usd": 0.1,
        "memory_mb": 512
    }'''

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/flow-costs/{cost_id}",
        method="PUT",
        status_code=200,
        request_body=api_flow_costs_cost_id_PUT_request_body
    )
    client.apply_mock(mock)

    # Execute Request
    api_flow_costs_cost_id_PUT_response = client.send_request(
        url=URL,
        path="/api/flow-costs/{cost_id}",
        method="PUT",
        body=api_flow_costs_cost_id_PUT_request_body,
        headers=headers,
        path_params={"cost_id": cost_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(api_flow_costs_cost_id_PUT_response, "20x")

    client.remove_all_mocks()


if __name__ == "__main__":
    test_api_flow_costs_cost_id_put()
