# Generated by Skyramp v1.3.14 on 2026-03-25 16:15:09.35870461 +0000 UTC m=+210.614899988
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_count-unique-constraint.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    count_POST_request_body = r'''{
        "deployment_filter": {},
        "flow_filter": {},
        "flow_run_filter": {},
        "task_run_filter": {},
        "work_pool_filter": {}
    }'''
    
    # Execute Request
    count_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/artifacts/count",
        method="POST",
        body=count_POST_request_body
    )
    # Generated Assertions
    assert count_POST_response.status_code == 201

    # Request Body
    count_POST_1_request_body = r'''{
        "deployment_filter": {},
        "flow_filter": {},
        "flow_run_filter": {},
        "task_run_filter": {},
        "work_pool_filter": {}
    }'''
    
    # Execute Request
    count_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/artifacts/count",
        method="POST",
        body=count_POST_1_request_body
    )
    # Generated Assertions
    assert count_POST_1_response.status_code == 409


if __name__ == "__main__":
    test_integration()
