# Generated by Skyramp v1.3.14 on 2026-03-24 21:52:37.169099604 +0000 UTC m=+297.699299759
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--chaining-key id \
# 		--framework pytest \
# 		--language python \
# 		--output integration_flow_cost_crud_lifecycle.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow_cost_crud_lifecycle.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "compute_seconds": 120.5,
        "cost_center": "data-team",
        "external_cost_usd": 0.05,
        "flow_run_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "memory_mb": 512
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/api/flow-costs/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    flow_costs_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/api/flow-costs/{flow-costs}",
        method="GET",
        headers=headers,
        path_params={"flow-costs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert flow_costs_GET_response.status_code == 200

    # Request Body
    flow_costs_PUT_request_body = r'''{
        "compute_seconds": 240,
        "external_cost_usd": 0.1
    }'''
    
    # Execute Request
    flow_costs_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/api/flow-costs/{flow-costs}",
        method="PUT",
        body=flow_costs_PUT_request_body,
        headers=headers,
        path_params={"flow-costs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert flow_costs_PUT_response.status_code == 200

    # Execute Request
    flow_costs_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/api/flow-costs/{flow-costs}",
        method="DELETE",
        headers=headers,
        path_params={"flow-costs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert flow_costs_DELETE_response.status_code == 204

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "compute_seconds": 120.5,
        "cost_center": "data-engineering",
        "external_cost_usd": 0.05,
        "flow_run_id": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
        "memory_mb": 256
    }'''
    
    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/api/flow-costs/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        data_override={
            "compute_seconds": skyramp.get_response_value(flow_costs_GET_response, "compute_seconds"),
            "external_cost_usd": skyramp.get_response_value(flow_costs_GET_response, "external_cost_usd"),
            "flow_run_id": skyramp.get_response_value(flow_costs_GET_response, "flow_run_id")
        }
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 201

    # Execute Request
    flow_costs_flow_costs_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/{flow-costs}",
        method="GET",
        path_params={"flow-costs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert flow_costs_flow_costs_GET_response.status_code == 200

    # Request Body
    flow_costs_flow_costs_PUT_request_body = r'''{
        "compute_seconds": 240,
        "cost_center": "ml-training",
        "external_cost_usd": 0.1,
        "memory_mb": 512
    }'''
    
    # Execute Request
    flow_costs_flow_costs_PUT_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/{flow-costs}",
        method="PUT",
        body=flow_costs_flow_costs_PUT_request_body,
        path_params={"flow-costs": skyramp.get_response_value(endpoint_1_POST_response, "id")},
        data_override={"memory_mb": skyramp.get_response_value(flow_costs_GET_response, "memory_mb")}
    )
    # Generated Assertions
    assert flow_costs_flow_costs_PUT_response.status_code == 200

    # Execute Request
    flow_costs_flow_costs_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/{flow-costs}",
        method="DELETE",
        path_params={"flow-costs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert flow_costs_flow_costs_DELETE_response.status_code == 204


if __name__ == "__main__":
    test_integration()
