# Generated by Skyramp v1.3.14 on 2026-03-24 23:20:24.427751895 +0000 UTC m=+109.156542819
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-cost-create-retrieve.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "compute_seconds": 120.5,
        "cost_center": "ml-team",
        "external_cost_usd": 0.05,
        "flow_run_id": "f47ac10b-58cc-4372-a567-0e02b2c3d479",
        "memory_mb": 512
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    flow_costs_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/{flow-costs}",
        method="GET",
        headers=headers,
        path_params={"flow-costs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert flow_costs_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
