# Generated by Skyramp v1.3.14 on 2026-03-24 23:21:53.957877616 +0000 UTC m=+193.351711320
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output integration_flowcost_delete_integrity.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flowcost-delete-integrity-1742817600.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "compute_seconds": 300,
        "cost_center": "data-team",
        "external_cost_usd": 0.25,
        "flow_run_id": "c3d4e5f6-a7b8-9012-cdef-012345678901",
        "memory_mb": 1024
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    flow_costs_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/{flow-costs}",
        method="GET",
        headers=headers,
        path_params={"flow-costs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert flow_costs_GET_response.status_code == 200

    # Execute Request
    flow_costs_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/{flow-costs}",
        method="DELETE",
        headers=headers,
        path_params={"flow-costs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert flow_costs_DELETE_response.status_code == 204

    # Execute Request
    flow_costs_GET_1_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/{flow-costs}",
        method="GET",
        headers=headers,
        path_params={"flow-costs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert flow_costs_GET_1_response.status_code == 404


if __name__ == "__main__":
    test_integration()
