# Generated by Skyramp v1.3.14 on 2026-03-25 00:49:41.603414308 +0000 UTC m=+119.837651782
# Command: skyramp generate contract rest http://localhost:4200/api/artifacts/filter \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_contract_artifacts_filter_auth.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"artifacts":{},"flow_runs":{},"task_runs":{},"limit":10,"offset":0,"sort":"CREATED_DESC"} \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/artifacts/filter POST
def test_filter_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    filter_POST_request_body = r'''{
        "artifacts": {},
        "flow_runs": {},
        "limit": 10,
        "offset": 0,
        "sort": "CREATED_DESC",
        "task_runs": {}
    }'''

    # Execute Request
    filter_POST_response = client.send_request(
        url=URL,
        path="/api/artifacts/filter",
        method="POST",
        body=filter_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert filter_POST_response.status_code == 401


if __name__ == "__main__":
    test_filter_post()
