# Generated by Skyramp v1.3.14 on 2026-03-24 21:38:14.592678373 +0000 UTC m=+251.873146707
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs/{cost_id} \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method GET \
# 		--output test_flow_costs_get_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params cost_id=a1b2c3d4-e5f6-7890-abcd-ef1234567890 \
# 		--runtime local

# Import of required libraries
import os
import pytest
import skyramp
from skyramp import MockV2


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs/{cost_id} GET
def test_api_flow_costs_cost_id_get():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    cost_id = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"

    # Configure mock response
    mock = MockV2(
        url=URL,
        path="/api/flow-costs/{cost_id}",
        method="GET",
        status_code=200
    )
    client.apply_mock(mock)

    # Execute Request
    api_flow_costs_cost_id_GET_response = client.send_request(
        url=URL,
        path="/api/flow-costs/{cost_id}",
        method="GET",
        headers=headers,
        path_params={"cost_id": cost_id}
    )

    # Generated Assertions
    assert skyramp.check_status_code(api_flow_costs_cost_id_GET_response, "20x")

    client.remove_all_mocks()


if __name__ == "__main__":
    test_api_flow_costs_cost_id_get()
