# Generated by Skyramp v1.3.13 on 2026-03-20 04:50:54.218899012 +0000 UTC m=+267.825549955
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_run_stats_empty_flow.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-stats-empty-flow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "name": "test-flow-empty-stats-1742435200"
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    stats_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_runs}/stats",
        method="GET",
        path_params={"flow_runs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert stats_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
