# Generated by Skyramp v1.3.11 on 2026-03-09 18:53:26.34320945 +0000 UTC m=+143.673275511
# Command: skyramp generate integration rest \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_items_crud_lifecycle.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_items-crud-lifecycle.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:4200"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "description": "A test item for lifecycle testing",
        "name": "prefect-test-item",
        "tags": [
            "tag-1",
            "tag-2"
        ]
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/items/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    items_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/items/{items}",
        method="GET",
        path_params={"items": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert items_GET_response.status_code == 200

    # Request Body
    items_PATCH_request_body = r'''{
        "description": "Updated description",
        "name": "prefect-updated-item",
        "tags": [
            "updated-tag"
        ]
    }'''
    
    # Execute Request
    items_PATCH_response = client.send_request(
        url=URL_localhost,
        path="/api/items/{items}",
        method="PATCH",
        body=items_PATCH_request_body,
        path_params={"items": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert items_PATCH_response.status_code == 204

    # Execute Request
    items_DELETE_response = client.send_request(
        url=URL_localhost,
        path="/api/items/{items}",
        method="DELETE",
        path_params={"items": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert items_DELETE_response.status_code == 204

if __name__ == "__main__":
    test_integration()
