# Generated by Skyramp v1.3.14 on 2026-03-25 16:15:33.903030317 +0000 UTC m=+235.159225684
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_filter_unique_constraint.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_filter-unique-constraint.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    filter_POST_request_body = r'''{
        "artifacts": {},
        "deployments": {},
        "flow_runs": {},
        "flows": {},
        "limit": 10,
        "offset": 0,
        "sort": "CREATED_DESC",
        "task_runs": {}
    }'''
    
    # Execute Request
    filter_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/artifacts/filter",
        method="POST",
        body=filter_POST_request_body
    )
    # Generated Assertions
    assert filter_POST_response.status_code == 201

    # Request Body
    filter_POST_1_request_body = r'''{
        "artifacts": {},
        "deployments": {},
        "flow_runs": {},
        "flows": {},
        "limit": 10,
        "offset": 0,
        "sort": "CREATED_DESC",
        "task_runs": {}
    }'''
    
    # Execute Request
    filter_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/artifacts/filter",
        method="POST",
        body=filter_POST_1_request_body
    )
    # Generated Assertions
    assert filter_POST_1_response.status_code == 409


if __name__ == "__main__":
    test_integration()
