# Generated by Skyramp v1.3.11 on 2026-03-09 18:53:44.422951663 +0000 UTC m=+161.753017725
# Command: skyramp generate integration rest \
# 		--chaining-key response.id \
# 		--framework pytest \
# 		--language python \
# 		--output test_items_filter_count_workflow.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_items-filter-count-workflow.json

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL_localhost = "http://localhost:4200"

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_1_POST_request_body = r'''{
        "description": "Item for filter and count testing",
        "name": "prefect-filter-test-item",
        "tags": [
            "filter-tag",
            "test"
        ]
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/items/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    filter_POST_request_body = r'''{
        "limit": 10,
        "offset": 0
    }'''
    
    # Execute Request
    filter_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/items/filter",
        method="POST",
        body=filter_POST_request_body
    )
    # Generated Assertions
    assert filter_POST_response.status_code == 200

    # Request Body
    count_POST_request_body = r'''{}'''
    
    # Execute Request
    count_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/items/count",
        method="POST",
        body=count_POST_request_body
    )
    # Generated Assertions
    assert count_POST_response.status_code == 200

if __name__ == "__main__":
    test_integration()
