# Generated by Skyramp v1.3.13 on 2026-03-20 04:50:16.163171636 +0000 UTC m=+229.769822579
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_run_stats_not_found.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-stats-not-found.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Execute Request
    stats_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/00000000-0000-0000-0000-000000000001/stats",
        method="GET"
    )
    # Generated Assertions
    assert stats_GET_response.status_code == 404


if __name__ == "__main__":
    test_integration()
