# Generated by Skyramp v1.3.14 on 2026-03-24 21:38:31.84017153 +0000 UTC m=+295.408568279
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_costs_budget_spend_tracking.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-costs-budget-spend-tracking.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    cost_center = "ml-team"

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "compute_seconds": 200,
        "cost_center": "ml-team",
        "external_cost_usd": 2.5,
        "flow_run_id": "f6a7b8c9-d0e1-2345-abcd-567890123456",
        "memory_mb": 1024
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers,
        data_override={"cost_center": cost_center}
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_2_POST_request_body = r'''{
        "alert_threshold_pct": 75,
        "cost_center": "ml-team",
        "monthly_budget_usd": 100
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/budgets/",
        method="POST",
        body=endpoint_2_POST_request_body,
        headers=headers,
        data_override={"cost_center": cost_center}
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Execute Request
    budgets_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/budgets/{budgets}",
        method="GET",
        headers=headers,
        path_params={"budgets": cost_center}
    )
    # Generated Assertions
    assert budgets_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
