# Generated by Skyramp v1.3.14 on 2026-03-24 21:38:02.723007219 +0000 UTC m=+266.291403978
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_costs_budget_unique_constraint.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-costs-budget-unique-constraint.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "alert_threshold_pct": 80,
        "cost_center": "engineering",
        "monthly_budget_usd": 500
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/budgets/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "alert_threshold_pct": 90,
        "cost_center": "engineering",
        "monthly_budget_usd": 750
    }'''
    
    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/budgets/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 409


if __name__ == "__main__":
    test_integration()
