# Generated by Skyramp v1.3.14 on 2026-03-25 00:50:28.052076826 +0000 UTC m=+125.185845047
# Command: skyramp generate contract rest http://localhost:4200/api/install_system_block_types \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_contract_post_install_system_block_types.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/install_system_block_types POST
def test_install_system_block_types_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    install_system_block_types_POST_response = client.send_request(
        url=URL,
        path="/api/install_system_block_types",
        method="POST",
        headers=headers
    )

    # Generated Assertions
    assert install_system_block_types_POST_response.status_code == 401


if __name__ == "__main__":
    test_install_system_block_types_post()
