# Generated by Skyramp v1.3.11 on 2026-03-09 18:53:54.314840182 +0000 UTC m=+171.644906234
# Command: skyramp generate contract rest http://localhost:4200/api/items/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_items_contract.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--request-data {"name":"contract-test-item","description":"Item for contract testing","tags":["contract","test"]} \
# 		--response-status-code 201 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:4200"

# contract test for /api/items/ POST
def test_endpoint_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_POST_request_body = r'''{
        "description": "Item for contract testing",
        "name": "contract-test-item",
        "tags": [
            "contract",
            "test"
        ]
    }'''

    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/api/items/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert endpoint_POST_response.status_code == 201

if __name__ == "__main__":
    test_endpoint_post()
