# Generated by Skyramp v1.3.14 on 2026-03-25 00:50:10.068913276 +0000 UTC m=+107.202681497
# Command: skyramp generate contract rest http://localhost:4200/api/owned-by/{resource_id:str} \
# 		--framework pytest \
# 		--language python \
# 		--method DELETE \
# 		--output test_contract_delete_owned_by.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/owned-by/{resource_id}:str DELETE
def test_owned_by_resource_id_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Execute Request
    owned_by_resource_id_DELETE_response = client.send_request(
        url=URL,
        path="/api/owned-by/{resource_id}:str",
        method="DELETE",
        headers=headers
    )

    # Generated Assertions
    assert owned_by_resource_id_DELETE_response.status_code == 401


if __name__ == "__main__":
    test_owned_by_resource_id_delete()
