# Generated by Skyramp v1.3.14 on 2026-03-24 21:37:31.605128502 +0000 UTC m=+235.173525271
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs/ \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_flow_costs_contract_auth.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flow_run_id":"e5f6a7b8-c9d0-1234-efab-345678901234","compute_seconds":30.0,"memory_mb":128.0,"external_cost_usd":0.0,"cost_center":"ops-team"} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs/ POST
def test_flow_costs_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flow_costs_POST_request_body = r'''{
        "compute_seconds": 30,
        "cost_center": "ops-team",
        "external_cost_usd": 0,
        "flow_run_id": "e5f6a7b8-c9d0-1234-efab-345678901234",
        "memory_mb": 128
    }'''

    # Execute Request
    flow_costs_POST_response = client.send_request(
        url=URL,
        path="/api/flow-costs/",
        method="POST",
        body=flow_costs_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert skyramp.check_status_code(flow_costs_POST_response, "20x")


if __name__ == "__main__":
    test_flow_costs_post()
