# Generated by Skyramp v1.3.14 on 2026-03-25 16:15:48.605650434 +0000 UTC m=+254.719641759
# Command: skyramp generate contract rest http://localhost:4200/api/flow-costs/ \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_contract_flow_costs_post.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--request-data {"flow_run_id":"770e8400-e29b-41d4-a716-446655440003","compute_seconds":600.0,"memory_mb":128.0,"external_cost_usd":0.0,"cost_center":"data-pipeline"} \
# 		--response-status-code 201 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/flow-costs/ POST
def test_flow_costs_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    flow_costs_POST_request_body = r'''{
        "compute_seconds": 600,
        "cost_center": "data-pipeline",
        "external_cost_usd": 0,
        "flow_run_id": "770e8400-e29b-41d4-a716-446655440003",
        "memory_mb": 128
    }'''

    # Execute Request
    flow_costs_POST_response = client.send_request(
        url=URL,
        path="/api/flow-costs/",
        method="POST",
        body=flow_costs_POST_request_body,
        headers=headers
    )

    # Generated Assertions
    assert flow_costs_POST_response.status_code == 201


if __name__ == "__main__":
    test_flow_costs_post()
