# Generated by Skyramp v1.3.14 on 2026-03-25 16:15:49.494837151 +0000 UTC m=+250.751032528
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_integration_increment_unique_constraint.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_increment-unique-constraint.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    increment_POST_request_body = r'''{
        "names": [
            "test-tag-unique"
        ],
        "task_run_id": "a3f7c2d1-84e5-4b9f-b6a2-c1d3e5f70812"
    }'''
    
    # Execute Request
    increment_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/concurrency_limits/increment",
        method="POST",
        body=increment_POST_request_body
    )
    # Generated Assertions
    assert increment_POST_response.status_code == 201

    # Request Body
    increment_POST_1_request_body = r'''{
        "names": [
            "test-tag-unique"
        ],
        "task_run_id": "a3f7c2d1-84e5-4b9f-b6a2-c1d3e5f70812"
    }'''
    
    # Execute Request
    increment_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/concurrency_limits/increment",
        method="POST",
        body=increment_POST_1_request_body
    )
    # Generated Assertions
    assert increment_POST_1_response.status_code == 409


if __name__ == "__main__":
    test_integration()
