# Generated by Skyramp v1.3.14 on 2026-03-25 00:49:31.961130876 +0000 UTC m=+110.195368350
# Command: skyramp generate contract rest http://localhost:4200/api/automations/owned-by/{resource_id} \
# 		--framework pytest \
# 		--language python \
# 		--method DELETE \
# 		--output test_contract_automations_owned_by_auth.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--path-params resource_id=prefect.flow-run.a1b2c3d4-e5f6-7890-abcd-ef1234567890 \
# 		--provider \
# 		--response-status-code 401 \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

# contract test for /api/automations/owned-by/{resource_id} DELETE
def test_owned_by_resource_id_delete():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Declaration of variables
    resource_id = "prefect.flow-run.a1b2c3d4-e5f6-7890-abcd-ef1234567890"

    # Execute Request
    owned_by_resource_id_DELETE_response = client.send_request(
        url=URL,
        path="/api/automations/owned-by/{resource_id}",
        method="DELETE",
        headers=headers,
        path_params={"resource_id": resource_id}
    )

    # Generated Assertions
    assert owned_by_resource_id_DELETE_response.status_code == 401


if __name__ == "__main__":
    test_owned_by_resource_id_delete()
