# Generated by Skyramp v1.3.13 on 2026-03-20 04:51:39.999453068 +0000 UTC m=+313.606104011
# Command: skyramp generate integration rest \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_run_stats_workflow.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--provider \
# 		--runtime local \
# 		--skipProvisionParents \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-stats-multi-state-workflow.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Request Body
    endpoint_2_POST_request_body = r'''{
        "name": "test-flow-multi-state-1742435200"
    }'''
    
    # Execute Request
    endpoint_2_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flows/",
        method="POST",
        body=endpoint_2_POST_request_body
    )
    # Generated Assertions
    assert endpoint_2_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_request_body = '{"flow_id": "' + skyramp.get_response_value(endpoint_2_POST_response, "id") + '", "name": "test-run-completed-1742435200"}'
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/",
        method="POST",
        body=endpoint_1_POST_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    set_state_POST_request_body = r'''{
        "force": true,
        "state": {
            "message": "First run completed",
            "name": "Completed",
            "type": "COMPLETED"
        }
    }'''
    
    # Execute Request
    set_state_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_runs}/set_state",
        method="POST",
        body=set_state_POST_request_body,
        path_params={"flow_runs": skyramp.get_response_value(endpoint_1_POST_response, "id")}
    )
    # Generated Assertions
    assert set_state_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_1_request_body = '{"flow_id": "' + skyramp.get_response_value(endpoint_2_POST_response, "id") + '", "name": "test-run-failed-1742435200"}'
    
    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/",
        method="POST",
        body=endpoint_1_POST_1_request_body
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 201

    # Request Body
    set_state_POST_1_request_body = r'''{
        "force": true,
        "state": {
            "message": "Second run failed",
            "name": "Failed",
            "type": "FAILED"
        }
    }'''
    
    # Execute Request
    set_state_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_runs}/set_state",
        method="POST",
        body=set_state_POST_1_request_body,
        path_params={"flow_runs": skyramp.get_response_value(endpoint_1_POST_1_response, "id")}
    )
    # Generated Assertions
    assert set_state_POST_1_response.status_code == 201

    # Execute Request
    stats_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow_runs/{flow_runs}/stats",
        method="GET",
        path_params={"flow_runs": skyramp.get_response_value(endpoint_2_POST_response, "id")}
    )
    # Generated Assertions
    assert stats_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
