# Generated by Skyramp v1.3.11 on 2026-03-09 18:53:54.382136367 +0000 UTC m=+171.712202429
# Command: skyramp generate fuzz rest http://localhost:4200/api/items/ \
# 		--framework pytest \
# 		--language python \
# 		--method POST \
# 		--output test_items_fuzz.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--request-data {"name":"fuzz-test-item","description":"Item for fuzz testing","tags":["fuzz","test"]} \
# 		--runtime local

# Import of required libraries
import skyramp
import os
import time
# URL for test requests
URL = "http://localhost:4200"

# fuzz test for /api/items/ POST
def test_endpoint_post():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = "Bearer " + os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_POST_request_body = r'''{
      "name": "fuzz-test-item",
      "description": "Item for fuzz testing",
      "tags": [
        "fuzz",
        "test"
      ]
    }'''
    
    # Fuzz strategies
    endpoint_post_fuzzed_body = {
        "description": "0123456789",
        "name": "0123456789",
        "tags": [
            "0123456789",
                "0123456789"
        ]
    }
    # Fuzz status codes
    expected_endpoint_post_status_code = {
        "description": "40x",
        "name": "40x",
        "tags": [
            "40x",
                "40x"
        ]
    }
    # Fuzz status codes for Null values
    expected_endpoint_post_null_status_code = {
        "description": "40x",
        "name": "40x",
        "tags": [
            "40x",
                "40x"
        ]
    }

    # Execute Request
    endpoint_POST_response = client.send_request(
        url=URL,
        path="/api/items/",
        method="POST",
        body=endpoint_POST_request_body,
        headers=headers,
        expected_code="20x"
    )

    for key in skyramp.iterate(endpoint_post_fuzzed_body):
        # Execute Request
        endpoint_POST_response = client.send_request(
            url=URL,
            path="/api/items/",
            method="POST",
            body=endpoint_POST_request_body,
            headers=headers,
            data_override={key: skyramp.get_value(endpoint_post_fuzzed_body, key)},
            expected_code=skyramp.get_value(expected_endpoint_post_status_code, key),
            description=f'Fuzzing request body { key } to { skyramp.get_value(endpoint_post_fuzzed_body, key) }'
        )

        # Execute Request
        endpoint_POST_response = client.send_request(
            url=URL,
            path="/api/items/",
            method="POST",
            body=endpoint_POST_request_body,
            headers=headers,
            data_override={key: None},
            expected_code=skyramp.get_value(expected_endpoint_post_null_status_code, key),
            description=f'Fuzzing request body { key } to None'
        )

    assert client.is_success()


if __name__ == "__main__":
    test_endpoint_post()
