# Generated by Skyramp v1.3.14 on 2026-03-24 21:38:58.563630089 +0000 UTC m=+322.132026848
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_costs_summary_aggregation.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-costs-summary-aggregation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "compute_seconds": 60,
        "cost_center": "analytics",
        "external_cost_usd": 0.25,
        "flow_run_id": "c9d0e1f2-a3b4-5678-defa-890123456789",
        "memory_mb": 256
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Request Body
    endpoint_1_POST_1_request_body = r'''{
        "compute_seconds": 90,
        "cost_center": "analytics",
        "external_cost_usd": 0.75,
        "flow_run_id": "e1f2a3b4-c5d6-7890-fabc-012345678901",
        "memory_mb": 384
    }'''
    
    # Execute Request
    endpoint_1_POST_1_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/",
        method="POST",
        body=endpoint_1_POST_1_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_1_response.status_code == 201

    # Execute Request
    endpoint_2_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/summary/",
        method="GET",
        headers=headers,
        query_params={"cost_center": ["analytics"]}
    )
    # Generated Assertions
    assert endpoint_2_GET_response.status_code == 200


if __name__ == "__main__":
    test_integration()
