# Generated by Skyramp v1.3.14 on 2026-03-24 21:38:27.981280352 +0000 UTC m=+265.261748696
# Command: skyramp generate integration rest \
# 		--auth-header Authorization \
# 		--framework pytest \
# 		--language python \
# 		--output test_flow_costs_cross_user_isolation.py \
# 		--output-dir /home/runner/work/prefect-testb/prefect-testb/tests \
# 		--overwrite \
# 		--runtime local \
# 		--trace /home/runner/work/prefect-testb/prefect-testb/tests/scenario_flow-costs-cross-user-isolation.json

# Import of required libraries
import skyramp
import os
import time


# URL for test requests
URL_localhost = skyramp.get_base_url("SKYRAMP_TEST_BASE_URL", "http://localhost:4200")

def test_integration():
    # Invocation of Skyramp Client
    client = skyramp.Client()
    # Definition of authentication header
    headers = {}
    if os.getenv("SKYRAMP_TEST_TOKEN") is not None:
        headers["Authorization"] = os.getenv("SKYRAMP_TEST_TOKEN")

    # Request Body
    endpoint_1_POST_request_body = r'''{
        "compute_seconds": 120.5,
        "cost_center": "engineering",
        "external_cost_usd": 0.05,
        "flow_run_id": "550e8400-e29b-41d4-a716-446655440001",
        "memory_mb": 256
    }'''
    
    # Execute Request
    endpoint_1_POST_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/",
        method="POST",
        body=endpoint_1_POST_request_body,
        headers=headers
    )
    # Generated Assertions
    assert endpoint_1_POST_response.status_code == 201

    # Execute Request
    flow_costs_99999999_9999_9999_9999_999999999999_GET_response = client.send_request(
        url=URL_localhost,
        path="/api/flow-costs/99999999-9999-9999-9999-999999999999",
        method="GET",
        headers=headers
    )
    # Generated Assertions
    assert flow_costs_99999999_9999_9999_9999_999999999999_GET_response.status_code == 404


if __name__ == "__main__":
    test_integration()
